---
services:
  cert-updater:
    image: fwinkler79/arm64v8-dehydrated-letsencrypt-updater:1.0.0
    container_name: cert-updater
    network_mode: host
    dns:
      - 8.8.8.8   # required due to some alpine issue with not resolving names properly.
    environment:
      - PUID=1000
      - PGID=1000
      # (Mandatory) Your Duck DNS API token.
      - DUCK_DNS_TOKEN="<your Duck DNS API token>"

      # (Optional) The Let's Encrypt URL to use. 
      # Possible values are:
      #  For staging:    https://acme-staging-v02.api.letsencrypt.org/directory (default)
      #  For production: https://acme-v02.api.letsencrypt.org/directory         (beware rate limiting!)
      #- CA_URL=https://acme-staging-v02.api.letsencrypt.org/directory

      # (Optional) The number of days before expiry that a cert
      # should be refreshed. 
      # Default: 35
      #- RENEW_DAYS_BEFORE_EXPIRY=35

      # (Optional) The time to wait for DNS challenge to have propagated.
      # Default: 60
      #- DNS_CHALLENGE_PROPAGATION_TIME=60
    volumes:
      # Map the host's docker socket into the container
      # As a result the docker client in the container can
      # interact with the host's docker daemon, thus controlling
      # the host docker from within the container.
      - /var/run/docker.sock:/var/run/docker.sock
      # The user configurations of this docker image.
      - ./dehydrated/configurations:/dehydrated/configurations
      # The output folder where certificates will be stored.
      - ./dehydrated/certificates:/dehydrated/certificates
